### ISSUE TITLE
OAuth2 authentication doesn't work for me

### ISSUE THREAD

**Issue by Akunamatata2050** [IntuitDeveloper/OAuth2PythonSampleApp#1]
I created new app named 'xxx-dev' at INTUIT about 6 days ago.
I followed the instruction and i enabled "Quickbooks Accounting" and "Quickbooks Payments" on App Settings page.
And i was implementing Quickbooks Online Authentication in my Rails app using my Client ID and Client Secret.
I was using OAuth2 but i get error continuosly.
So i tried this sample app but i get error too.
They say that "We're sorry! We are experiencing some problems. Please try again later.".
Looking forward your help.

**Comment by rana-ahmed** [comment]
I am facing this problem too
![screenshot from 2017-07-29 13-21-14](https://user-images.githubusercontent.com/9111402/28743044-d4c66c20-7461-11e7-9339-5b0a30aea466.png)

**Comment by nbhambhani** [comment]
This error is primarily because of invalid/incorrect redirect_uri on the app's settings. Correct redirect_uri is http://localhost:8000/sampleappoauth2/authCodeHandler

**Comment by nbhambhani** [comment]
Closing this issue since it's resolved.
